// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {BlsHashToCurve} from "../src/crypto/BlsHashToCurve.sol";

/// @title BlsHashToCurveTest
/// @notice Gate-0 golden-vector test for the BLS12-381 hash-to-G2 kernel.
///
///         Tests that on-chain hashToG2(msg) matches py_ecc G2ProofOfPossession
///         hash_to_G2(msg, DST_SIG) byte-for-byte under evm_version=prague.
///
///         Vectors generated by py_ecc (installed at /tmp/relayer-venv):
///           from py_ecc.bls.hash_to_curve import hash_to_G2
///           from py_ecc.bls.ciphersuites import G2ProofOfPossession
///           DST = G2ProofOfPossession.DST  # b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_"
///           pt = hash_to_G2(msg, DST, hashlib.sha256)
///           Encoding: normalize(pt) -> x.c0||x.c1||y.c0||y.c1 (EIP-2537, c0 first)
///           Each Fp: 16 zero bytes || 48-byte big-endian.
///
///         CLASSICAL (Shor-breakable) BLS12-381 -- NOT post-quantum.
///         This kernel only; full verifier wiring is flagged for Jacob-Strokus
///         (coordination required for uncompressed-key storage-layout change).
///
///         Run with: FOUNDRY_PROFILE=prague forge test --match-contract BlsHashToCurve
///
///         Tests that depend on EIP-2537 (all hashToG2 tests, the G1ADD smoke)
///         are skipped via vm.skip() when run under a non-prague profile (e.g.
///         default/cancun CI). Tests that do not use EIP-2537 precompiles (DST
///         sanity checks, expand_message_xmd) run on any profile.
contract BlsHashToCurveTest is Test {
    using stdJson for string;

    // EIP-2537 precompile probe address
    address internal constant BLS12_G1ADD = address(0x0b);

    // G1 generator in EIP-2537 128-byte form; used to probe EIP-2537 availability
    bytes internal constant G1_GEN =
        hex"0000000000000000000000000000000017f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb"
        hex"0000000000000000000000000000000008b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1";

    // Set in setUp() -- true only when EIP-2537 returns a non-empty result
    bool internal eip2537Active;

    // -------------------------------------------------------------------------
    // Inline golden vectors (py_ecc, EIP-2537 256-byte encoding)
    // Layout: x.c0(64B) || x.c1(64B) || y.c0(64B) || y.c1(64B)
    // Each Fp = 16-zero-pad || 48-byte big-endian (c0 first = py_ecc coeffs[0])
    // -------------------------------------------------------------------------

    // Vector 0: msg = bytes32(1)
    bytes internal constant MSG_0 =
        hex"0000000000000000000000000000000000000000000000000000000000000001";

    // solhint-disable max-line-length
    bytes internal constant EXPECTED_G2_0 =
        hex"0000000000000000000000000000000010cdbd4a3cf7ea4bb500a5518c16741f80cc38c42cb8c9941d6f5334afe7cd3e64456d914c889c3d42f96b853ced27a70000000000000000000000000000000014f5250898d3a6e4535e356cc4ea8a751c44cd17f7628edbea5ec60748d5cfec1df7b3ad6b1e536e4ef001060617856900000000000000000000000000000000049ebeb6128ad3f7e18a07b9720c3f68a6a6380afae8ae70e22e7360d5d5ae1f11040f531f41accf9de304d08f04da820000000000000000000000000000000001d7faded9d3d5400590f556f4638955112765e9f437517103318c32dc278766713c4500da5f7e0471581e5661702492";

    // Vector 1: msg = 0xdeadbeefcafebabe...
    bytes internal constant MSG_1 =
        hex"deadbeefcafebabe0123456789abcdef0123456789abcdef0123456789abcdef";

    bytes internal constant EXPECTED_G2_1 =
        hex"0000000000000000000000000000000001f94ab1c05b9c3c07605384bb3522d5a3b3a0610a0f22fed59c9904245c8c20e12d524ef843ef18aaab50e4d1a852fd000000000000000000000000000000000c4c547b462fca4e4b0c2fb1627f586c0caede3c032c5c5dcec7e63b69e8addaa9aea2f6d309290b20abfa77a92188d50000000000000000000000000000000016265d011c0946076ddff1e8b053c7a67a0a7322c3d2f2bde57b7283f18e6437d7e7c895c3ee41178e0ea1aeacd9c3410000000000000000000000000000000004f44440d629ba242db6db8a3e1793c2f107c4b7b722d3c34cfc23057d21fe8d60efa003a1ac12c378669de5c6d1039d";
    // solhint-enable max-line-length

    // -------------------------------------------------------------------------
    // setUp: probe EIP-2537 availability
    // -------------------------------------------------------------------------

    function setUp() external {
        // Probe G1ADD (0x0b): under prague it returns 128 bytes; under cancun it
        // returns 0 bytes (empty account call). Gate all EIP-2537-dependent tests.
        bytes memory input = abi.encodePacked(G1_GEN, G1_GEN);
        (, bytes memory result) = BLS12_G1ADD.staticcall(input);
        eip2537Active = result.length == 128;
    }

    // -------------------------------------------------------------------------
    // expand_message_xmd unit test (no EIP-2537; runs on any profile)
    // -------------------------------------------------------------------------

    /// @notice Verify expand_message_xmd produces the correct 256-byte output.
    ///         Cross-checked against the Python RFC 9380 reference implementation.
    ///         Python: expand_message_xmd(MSG_0, DST_SIG, 256)
    ///           b_1 (bytes  0..31)  = 6511a9bc...18e8f
    ///           b_8 (bytes 224..255) = d1d9e18a...3dbae
    function test_expandMessageXmd_msg0_crossCheck() external view {
        bytes memory result = BlsHashToCurveHarness(address(this)).expandMessageXmd(MSG_0);
        assertEq(result.length, 256, "expand_message_xmd: wrong length");

        // b_1 = SHA-256(b_0 || 0x01 || DST_prime)
        // forge-lint: disable-next-line(unsafe-typecast)
        bytes32 first32 = bytes32(result); // result is 256-byte output; take first 32B
        assertEq(
            first32,
            // forge-lint: disable-next-line(unsafe-typecast)
            bytes32(
                hex"6511a9bca18015f53edb35c80cde5decae23023908399c04c24cb9cfce618e8f"
            ),
            "expand_message_xmd: b_1 mismatch vs Python"
        );

        // b_8 at bytes 224..255 (last 32 bytes, i=8)
        bytes32 last32;
        assembly {
            last32 := mload(add(add(result, 32), 224))
        }
        assertEq(
            last32,
            // forge-lint: disable-next-line(unsafe-typecast)
            bytes32(
                hex"d1d9e18ae4fe6d03e3cc83a843d9d6454043732d6e1b4bb26c7999804b83dbae"
            ),
            "expand_message_xmd: b_8 mismatch vs Python"
        );
    }

    // -------------------------------------------------------------------------
    // Golden-vector tests (require EIP-2537 / prague; skip otherwise)
    // -------------------------------------------------------------------------

    /// @notice LOAD-BEARING GATE: hashToG2(MSG_0) must byte-match py_ecc vector.
    ///         Proves the on-chain H2C kernel matches the Python signer.
    ///         Skipped when EIP-2537 precompiles are not active (non-prague profile).
    function test_hashToG2_golden_msg0() external {
        if (!eip2537Active) {
            vm.skip(true);
            return;
        }
        bytes memory result = BlsHashToCurveHarness(address(this)).hashToG2(MSG_0);
        assertEq(result.length, 256, "hashToG2: wrong output length");
        assertEq(result, EXPECTED_G2_0, "hashToG2(MSG_0): byte mismatch with py_ecc golden vector");
    }

    /// @notice LOAD-BEARING GATE: hashToG2(MSG_1) must byte-match py_ecc vector.
    ///         Skipped when EIP-2537 precompiles are not active (non-prague profile).
    function test_hashToG2_golden_msg1() external {
        if (!eip2537Active) {
            vm.skip(true);
            return;
        }
        bytes memory result = BlsHashToCurveHarness(address(this)).hashToG2(MSG_1);
        assertEq(result.length, 256, "hashToG2: wrong output length");
        assertEq(result, EXPECTED_G2_1, "hashToG2(MSG_1): byte mismatch with py_ecc golden vector");
    }

    // -------------------------------------------------------------------------
    // Fixture-file redundancy check (require EIP-2537; skip otherwise)
    // -------------------------------------------------------------------------

    /// @notice Load vectors from JSON fixture and re-assert golden match.
    ///         Skipped when EIP-2537 precompiles are not active (non-prague profile).
    function test_hashToG2_fixtureFile_msg0() external {
        if (!eip2537Active) {
            vm.skip(true);
            return;
        }
        string memory json = vm.readFile("test/fixtures/bls/h2c_vectors.json");
        bytes memory fixtureMsg = json.readBytes(".vectors[0].msg");
        bytes memory fixtureG2 = json.readBytes(".vectors[0].g2_eip2537");
        assertEq(fixtureMsg, MSG_0, "fixture msg_0 mismatch");
        assertEq(fixtureG2, EXPECTED_G2_0, "fixture g2_0 mismatch");
        bytes memory result = BlsHashToCurveHarness(address(this)).hashToG2(fixtureMsg);
        assertEq(result, fixtureG2, "hashToG2(fixture msg_0): byte mismatch");
    }

    function test_hashToG2_fixtureFile_msg1() external {
        if (!eip2537Active) {
            vm.skip(true);
            return;
        }
        string memory json = vm.readFile("test/fixtures/bls/h2c_vectors.json");
        bytes memory fixtureMsg = json.readBytes(".vectors[1].msg");
        bytes memory fixtureG2 = json.readBytes(".vectors[1].g2_eip2537");
        assertEq(fixtureMsg, MSG_1, "fixture msg_1 mismatch");
        assertEq(fixtureG2, EXPECTED_G2_1, "fixture g2_1 mismatch");
        bytes memory result = BlsHashToCurveHarness(address(this)).hashToG2(fixtureMsg);
        assertEq(result, fixtureG2, "hashToG2(fixture msg_1): byte mismatch");
    }

    // -------------------------------------------------------------------------
    // DST sanity checks (no EIP-2537; runs on any profile)
    // -------------------------------------------------------------------------

    /// @notice Verify DST_SIG bytes match the expected ASCII string.
    function test_dstSig_bytesMatch() external pure {
        bytes memory dst = BlsHashToCurve.DST_SIG;
        assertEq(dst.length, 43, "DST_SIG length must be 43");
        assertEq(
            dst,
            bytes("BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_"),
            "DST_SIG must match py_ecc G2ProofOfPossession.DST exactly"
        );
    }

    function test_dstPop_bytesMatch() external pure {
        bytes memory dst = BlsHashToCurve.DST_POP;
        // py_ecc G2ProofOfPossession.POP_TAG = b"BLS_POP_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_" = 43 bytes
        assertEq(dst.length, 43, "DST_POP length must be 43");
        assertEq(
            dst,
            bytes("BLS_POP_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_"),
            "DST_POP must match py_ecc G2ProofOfPossession.POP_TAG exactly"
        );
    }

    // -------------------------------------------------------------------------
    // Self-delegation helpers (harness functions called on this contract)
    // -------------------------------------------------------------------------

    function expandMessageXmd(bytes memory msg) external view returns (bytes memory) {
        return BlsHashToCurve._expandMessageXmd(msg, BlsHashToCurve.DST_SIG, 256);
    }

    function hashToG2(bytes memory msg) external view returns (bytes memory) {
        return BlsHashToCurve.hashToG2(msg);
    }
}

// -------------------------------------------------------------------------
// Harness: separate contract for clearer test isolation
// -------------------------------------------------------------------------

/// @dev Minimal harness that wraps BlsHashToCurve internal functions.
contract BlsHashToCurveHarness {
    function hashToG2(bytes memory msg) external view returns (bytes memory) {
        return BlsHashToCurve.hashToG2(msg);
    }

    function expandMessageXmd(bytes memory msg) external view returns (bytes memory) {
        return BlsHashToCurve._expandMessageXmd(msg, BlsHashToCurve.DST_SIG, 256);
    }
}
