// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {GsxDagValidatorRegistry} from "../src/verifiers/GsxDagValidatorRegistry.sol";
import {Sp1QuorumVerifier} from "../src/verifiers/Sp1QuorumVerifier.sol";

// ---------------------------------------------------------------------------
// Mock SP1 verifier
// ---------------------------------------------------------------------------

/// @notice MockSP1Verifier: verifyProof reverts iff proof[0] != 0x01.
///         Mirrors the pattern in ZKBridgeVerifier.t.sol (MockSP1VerifierLocal).
///         Returns void (like the real ISP1Verifier) — a revert means invalid.
contract MockSP1Verifier {
    function verifyProof(
        bytes32, /* programVKey — not checked in mock */
        bytes calldata, /* publicValues — verified by Sp1QuorumVerifier before this call */
        bytes calldata proof
    )
        external
        pure
    {
        require(proof.length > 0 && proof[0] == 0x01, "MockSP1Verifier: invalid proof");
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// @notice Sp1QuorumVerifier integration test.
///
/// ## Cross-check: guest ↔ registry encoding
/// The `EXPECTED_VALIDATOR_SET_ROOT` constant below is the value produced by
/// the sp1-quorum-host execute run for the same 4-validator set. Both the
/// Rust guest and this Solidity registry must compute identical roots.
///
/// Canonical encoding (both guest and registry):
///   keccak256(
///     pkHash_0(32) || stake_0-as-uint256-BE(32) ||
///     pkHash_1(32) || stake_1-as-uint256-BE(32) ||
///     pkHash_2(32) || stake_2-as-uint256-BE(32) ||
///     pkHash_3(32) || stake_3-as-uint256-BE(32)
///   )
/// where validators are in strictly-increasing pkHash order.
///
/// Public values layout (128 bytes):
///   [0..32]   networkId    (bytes32)
///   [32..64]  blockNumber  (uint256 BE)
///   [64..96]  stateRoot    (bytes32)
///   [96..128] validatorSetRoot (bytes32)
contract Sp1QuorumVerifierTest is Test {
    GsxDagValidatorRegistry registry;
    Sp1QuorumVerifier verifier;
    MockSP1Verifier mockSP1;

    address admin = makeAddr("admin");

    // Network parameters (match sp1-quorum-host main.rs deterministic inputs)
    uint256 constant NETWORK_ID = 1; // networkId = 1 (v[31]=0x01)
    uint256 constant BLOCK_NUMBER = 42_000;
    // "test" = 0x74657374, padded to 32 bytes
    bytes32 constant STATE_ROOT =
        bytes32(0x7465737400000000000000000000000000000000000000000000000000000000);

    // Validator set: 4 validators, equal stake 25, derived from ML-DSA seeds 1-4.
    // pkHashes are keccak256(ML-DSA-65 verifying key bytes), sorted strictly-increasing.
    // Generated by sp1-quorum-host with seeds 1..4 and deterministic key generation.
    bytes32 constant PK_HASH_0 =
        bytes32(0x489db88ccf57feb970ec8f170290b8b43e8318cf42730a0b6162e56e7d150d84);
    bytes32 constant PK_HASH_1 =
        bytes32(0x902061fca1bbd86d48109cdf605457979f5d89e76d8b7dd68b6cb575ead3c320);
    bytes32 constant PK_HASH_2 =
        bytes32(0x9af7972eefd71cd3576ddcc8d10b4e2ae45d99f6a6fda96fd2e47d72a3f30a1d);
    bytes32 constant PK_HASH_3 =
        bytes32(0xf040b4e6b3f00456ed9a880cf139948a0978c970458d510cc2353f6293960c21);
    uint256 constant STAKE_EACH = 25;

    /// @dev validator_set_root produced by sp1-quorum-host execute mode.
    ///      Must equal registry.currentValidatorSetRoot() after bootstrap.
    ///      This is the LOAD-BEARING cross-check: if guest ↔ registry encoding
    ///      diverges, both cannot equal this same constant.
    bytes32 constant EXPECTED_VALIDATOR_SET_ROOT =
        bytes32(0xa6e9b8e6a80ec82cd47f0d51da2812a2b8f3d64e7314e1f05944b2da5dc2c500);

    bytes32 constant VKEY = keccak256("sp1-quorum-verifier-vkey-v1");

    function setUp() public {
        mockSP1 = new MockSP1Verifier();
        registry = new GsxDagValidatorRegistry(admin, NETWORK_ID);
        verifier = new Sp1QuorumVerifier(address(mockSP1), VKEY, address(registry));

        // Bootstrap epoch 0 with the deterministic validator set (same pkHashes/stakes
        // as the sp1-quorum-host test vectors).
        bytes32[] memory pkHashes = new bytes32[](4);
        pkHashes[0] = PK_HASH_0;
        pkHashes[1] = PK_HASH_1;
        pkHashes[2] = PK_HASH_2;
        pkHashes[3] = PK_HASH_3;

        uint256[] memory stakes = new uint256[](4);
        stakes[0] = STAKE_EACH;
        stakes[1] = STAKE_EACH;
        stakes[2] = STAKE_EACH;
        stakes[3] = STAKE_EACH;

        vm.prank(admin);
        registry.bootstrapEpoch0(pkHashes, stakes);
    }

    // -----------------------------------------------------------------------
    // Helper: build valid publicValues for a given validatorSetRoot
    // -----------------------------------------------------------------------

    function _buildPV(bytes32 vsr) internal pure returns (bytes memory) {
        return abi.encodePacked(
            bytes32(uint256(NETWORK_ID)), // networkId as bytes32
            uint256(BLOCK_NUMBER), // blockNumber as uint256
            STATE_ROOT, // stateRoot
            vsr // validatorSetRoot
        );
    }

    bytes constant VALID_PROOF = hex"01aabbcc"; // first byte 0x01 → mock accepts
    bytes constant BAD_PROOF = hex"00aabbcc"; // first byte 0x00 → mock rejects

    // -----------------------------------------------------------------------
    // 1. Cross-check: guest ↔ registry encoding (load-bearing)
    // -----------------------------------------------------------------------

    /// @notice The registry's currentValidatorSetRoot() must equal the value
    ///         committed by the sp1-quorum-verifier guest (EXPECTED_VALIDATOR_SET_ROOT).
    ///         If the encoding diverges, this test fails even if everything else passes.
    function test_validatorSetRoot_matchesGuestOutput() public view {
        bytes32 registryRoot = registry.currentValidatorSetRoot();
        assertEq(
            registryRoot,
            EXPECTED_VALIDATOR_SET_ROOT,
            "Registry root != guest-committed root: guest<->registry encoding mismatch!"
        );
    }

    // -----------------------------------------------------------------------
    // 2. Happy path: valid proof + matching publicValues + correct setRoot → finalizes
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_valid() public {
        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );

        assertEq(
            verifier.finalizedStateRoot(BLOCK_NUMBER),
            STATE_ROOT,
            "State root must be finalized after valid proof"
        );
    }

    // -----------------------------------------------------------------------
    // 3. Idempotency: second call with same root is a no-op (no revert)
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_idempotent() public {
        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );
        // Second call with identical parameters must not revert
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );
        assertEq(verifier.finalizedStateRoot(BLOCK_NUMBER), STATE_ROOT);
    }

    // -----------------------------------------------------------------------
    // 4. Conflicting root → revert HeaderConflict (equivocation guard)
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_conflictReverts() public {
        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );

        bytes32 differentRoot = keccak256("different");
        // Build publicValues with the different state root so PV check passes
        bytes memory conflictPV = abi.encodePacked(
            bytes32(uint256(NETWORK_ID)),
            uint256(BLOCK_NUMBER),
            differentRoot,
            EXPECTED_VALIDATOR_SET_ROOT
        );

        vm.expectRevert(
            abi.encodeWithSelector(Sp1QuorumVerifier.HeaderConflict.selector, BLOCK_NUMBER)
        );
        verifier.submitProvenHeader(
            BLOCK_NUMBER, differentRoot, EXPECTED_VALIDATOR_SET_ROOT, conflictPV, VALID_PROOF
        );
    }

    // -----------------------------------------------------------------------
    // 5. Wrong validatorSetRoot → revert ValidatorSetRootMismatch (binding load-bearing)
    //
    // NOTE: We submit internally-consistent publicValues that USE the wrong root,
    // so the publicValues check passes and the revert comes specifically from the
    // validatorSetRoot != registry.currentValidatorSetRoot() check.
    // This proves the registry-binding is load-bearing, not just the PV equality.
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_wrongValidatorSetRoot_reverts() public {
        bytes32 wrongRoot = keccak256("not-the-real-set");
        // Build publicValues consistent with wrongRoot so PV check passes
        bytes memory pvWithWrongRoot = _buildPV(wrongRoot);

        vm.expectRevert(
            abi.encodeWithSelector(
                Sp1QuorumVerifier.ValidatorSetRootMismatch.selector,
                wrongRoot,
                EXPECTED_VALIDATOR_SET_ROOT
            )
        );
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, wrongRoot, pvWithWrongRoot, VALID_PROOF
        );
    }

    // -----------------------------------------------------------------------
    // 6. SP1 verifier rejects proof → revert (bubbled from mock)
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_badProof_reverts() public {
        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        // MockSP1Verifier reverts on proof[0] != 0x01
        vm.expectRevert("MockSP1Verifier: invalid proof");
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, BAD_PROOF
        );
        assertEq(verifier.finalizedStateRoot(BLOCK_NUMBER), bytes32(0));
    }

    // -----------------------------------------------------------------------
    // 7. Tampered publicValues → revert PublicValuesMismatch
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_tamperedPV_reverts() public {
        bytes memory tamperedPV = abi.encodePacked(
            bytes32(uint256(NETWORK_ID + 1)), // wrong networkId
            uint256(BLOCK_NUMBER),
            STATE_ROOT,
            EXPECTED_VALIDATOR_SET_ROOT
        );

        vm.expectRevert(Sp1QuorumVerifier.PublicValuesMismatch.selector);
        verifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, tamperedPV, VALID_PROOF
        );
    }

    // -----------------------------------------------------------------------
    // 8. SP1 verifier has no code → revert SP1VerifierNotDeployed
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_noCodeVerifier_reverts() public {
        // Deploy verifier pointing to an EOA (no code)
        Sp1QuorumVerifier badVerifier =
            new Sp1QuorumVerifier(address(0xDEAD), VKEY, address(registry));

        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        vm.expectRevert(Sp1QuorumVerifier.SP1VerifierNotDeployed.selector);
        badVerifier.submitProvenHeader(
            BLOCK_NUMBER, STATE_ROOT, EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );
    }

    // -----------------------------------------------------------------------
    // 9. Zero stateRoot → revert ZeroStateRoot
    // -----------------------------------------------------------------------

    function test_submitProvenHeader_zeroStateRoot_reverts() public {
        bytes memory pv = _buildPV(EXPECTED_VALIDATOR_SET_ROOT);
        vm.expectRevert(Sp1QuorumVerifier.ZeroStateRoot.selector);
        verifier.submitProvenHeader(
            BLOCK_NUMBER, bytes32(0), EXPECTED_VALIDATOR_SET_ROOT, pv, VALID_PROOF
        );
    }
}
